resources:
  - ../../common

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx  
    releaseName: dev2-ingress-nginx
    namespace: dev2
    version: 4.10.1
    valuesFile: values.yaml
