controller:
  replicaCount: 2
  allowSnippetAnnotations: true
  service:
    type: ClusterIP
  ingressClassResource:
    default: false
    name: nginx-dev2
    controllerValue: k8s.io/ingress-nginx-dev2
  scope:
    enabled: true
    namespace: dev2

