apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: liferay
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: nginx
            repoURL: https://kubernetes.github.io/ingress-nginx
            chart: ingress-nginx 
            version: 4.10.1
    - list:
      elements:
        - env: dev1
        - env: dev2
        - env: dev3           

  template:
    metadata:
      name: '{{app}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{version}}'
        helm:
          valueFiles:
            - 'apps/{{app}}/values-{{env}}.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true