helmCharts:
  - name: liferay
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.14.1
    releaseName: ingress-nginx
    namespace: dev1
    includeCRDs: true
    valuesFile: values.yaml