resources:
  - ../../common

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    releaseName: dev4-ingress-nginx
    namespace: dev4
    version: 4.10.1
    valuesFile: values.yaml
