controller:
  replicaCount: 2
  allowSnippetAnnotations: true
  service:
    type: ClusterIP
  ingressClassResource:
    default: false
    name: nginx-dev3
    controllerValue: k8s.io/ingress-nginx-dev3
  scope:
    enabled: true
    namespace: dev3

