helmCharts:
  - name: liferay
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.9.0
    releaseName: ingress-nginx
    namespace: dev1
    namespace: dev3
    includeCRDs: true
    valuesFile: values.yaml